language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - golang
  ssh_known_hosts: 52.76.173.135
before_install:
  -  sudo pip install -U virtualenv pre-commit pip
  -  sudo pip install Jinja2==2.9.5
  -  sudo pip install docopt
  -  GOPATH=/tmp/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb          # change branch
  -  export DEPLOY_DOCS_SH=https://raw.githubusercontent.com/PaddlePaddle/PaddlePaddle.org/move_book_conversion_logic_to_PPO_script/scripts/deploy/deploy_docs.sh
  -  export TRAVIS_BRANCH=develop # debug purpose
script:
  -  PATH=/tmp/go/bin:$PATH .travis/precommit.sh
  # 1:CONTENT_DEC_PASSWD, 2:SOURCE_DIR, 3:VERSION
  - |
    curl $DEPLOY_DOCS_SH | bash -s $CONTENT_DEC_PASSWD book $TRAVIS_BRANCH
notifications:
  email:
    on_success: change
    on_failure: always
