language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  - JOB=PRE_COMMIT

addons:
  apt:
    packages:
      - git
      - python
      - python-pip
      - python2.7-dev
      - golang
  ssh_known_hosts: 52.76.173.135
before_install:
  -  sudo pip install -U virtualenv pre-commit pip
  -  sudo pip install Jinja2==2.9.5
  -  sudo pip install docopt
  -  GOPATH=/tmp/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb
script:
  -  PATH=/tmp/go/bin:$PATH .travis/precommit.sh
  - |
    export DEPLOY_DOCS_SH=https://raw.githubusercontent.com/PaddlePaddle/PaddlePaddle.org/develop/scripts/deploy/deploy_docs.sh
    export BOOK_DIR=`pwd`
    cd ..
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "develop"  ||  "$TRAVIS_BRANCH" =~ ^v[[:digit:]]+\.[[:digit:]]+(\.[[:digit:]]+)?(-\S*)?$ ]]; then curl $DEPLOY_DOCS_SH | bash -s $CONTENT_DEC_PASSWD $TRAVIS_BRANCH $BOOK_DIR; else echo "not develop branch, no deploy"; fi;
notifications:
  email:
    on_success: change
    on_failure: always
